kind: pipeline
type: docker
name: build-and-push-from-ci

steps:
  - name: check-docker
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - |
        echo "Checking Docker connection..."
        docker version
        echo ""
        echo "Docker is ready!"
        echo ""
        docker info | grep -E "Server Version|Storage Driver|Operating System" || true

  - name: build_and_push_to_dockerhub
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - |
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Starting Docker Build Process"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        
        echo "Logging into Docker Hub..."
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        echo "Login successful!"
        echo ""
        
        echo "Building Docker image..."
        echo "   Repository: reemsolimman/spring-petclinic"
        echo "   Commit: ${DRONE_COMMIT_SHA:0:8}"
        echo "   Build: ${DRONE_BUILD_NUMBER}"
        echo ""
        docker build -t reemsolimman/spring-petclinic:latest .
        echo "Build completed!"
        echo ""
        
        echo "Tagging images..."
        docker tag reemsolimman/spring-petclinic:latest reemsolimman/spring-petclinic:${DRONE_COMMIT_SHA:0:8}
        docker tag reemsolimman/spring-petclinic:latest reemsolimman/spring-petclinic:${DRONE_BUILD_NUMBER}
        echo "Tagged: latest, ${DRONE_COMMIT_SHA:0:8}, ${DRONE_BUILD_NUMBER}"
        echo ""
        
        echo "Pushing images to Docker Hub..."
        docker push reemsolimman/spring-petclinic:latest
        echo "   ✓ Pushed: latest"
        docker push reemsolimman/spring-petclinic:${DRONE_COMMIT_SHA:0:8}
        echo "   ✓ Pushed: ${DRONE_COMMIT_SHA:0:8}"
        docker push reemsolimman/spring-petclinic:${DRONE_BUILD_NUMBER}
        echo "   ✓ Pushed: ${DRONE_BUILD_NUMBER}"
        echo ""
        
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "SUCCESS! All images pushed to Docker Hub"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "Available images:"
        echo "   • reemsolimman/spring-petclinic:latest"
        echo "   • reemsolimman/spring-petclinic:${DRONE_COMMIT_SHA:0:8}"
        echo "   • reemsolimman/spring-petclinic:${DRONE_BUILD_NUMBER}"
        echo ""
        echo "View on Docker Hub:"
        echo "   https://hub.docker.com/r/reemsolimman/spring-petclinic/tags"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    exclude:
      - push
      - pull_request
      - tag
      - promote
      - rollback
      - cron
